/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutChooseWalletRouteImport } from './routes/_layout/choose-wallet'
import { Route as LayoutAuthRouteImport } from './routes/_layout/_auth'
import { Route as LayoutAuthSettingIndexRouteImport } from './routes/_layout/_auth/setting/index'
import { Route as LayoutAuthProfileIndexRouteImport } from './routes/_layout/_auth/profile/index'
import { Route as LayoutAuthChatIndexRouteImport } from './routes/_layout/_auth/chat/index'
import { Route as LayoutAuthChatChatIdRouteImport } from './routes/_layout/_auth/chat/chat.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutChooseWalletRoute = LayoutChooseWalletRouteImport.update({
  id: '/choose-wallet',
  path: '/choose-wallet',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthRoute = LayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthSettingIndexRoute = LayoutAuthSettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthProfileIndexRoute = LayoutAuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthChatIndexRoute = LayoutAuthChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthChatChatIdRoute = LayoutAuthChatChatIdRouteImport.update({
  id: '/chat/chat/$id',
  path: '/chat/chat/$id',
  getParentRoute: () => LayoutAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose-wallet': typeof LayoutChooseWalletRoute
  '/chat': typeof LayoutAuthChatIndexRoute
  '/profile': typeof LayoutAuthProfileIndexRoute
  '/setting': typeof LayoutAuthSettingIndexRoute
  '/chat/chat/$id': typeof LayoutAuthChatChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-wallet': typeof LayoutChooseWalletRoute
  '/chat': typeof LayoutAuthChatIndexRoute
  '/profile': typeof LayoutAuthProfileIndexRoute
  '/setting': typeof LayoutAuthSettingIndexRoute
  '/chat/chat/$id': typeof LayoutAuthChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_auth': typeof LayoutAuthRouteWithChildren
  '/_layout/choose-wallet': typeof LayoutChooseWalletRoute
  '/_layout/_auth/chat/': typeof LayoutAuthChatIndexRoute
  '/_layout/_auth/profile/': typeof LayoutAuthProfileIndexRoute
  '/_layout/_auth/setting/': typeof LayoutAuthSettingIndexRoute
  '/_layout/_auth/chat/chat/$id': typeof LayoutAuthChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose-wallet'
    | '/chat'
    | '/profile'
    | '/setting'
    | '/chat/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-wallet'
    | '/chat'
    | '/profile'
    | '/setting'
    | '/chat/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/_auth'
    | '/_layout/choose-wallet'
    | '/_layout/_auth/chat/'
    | '/_layout/_auth/profile/'
    | '/_layout/_auth/setting/'
    | '/_layout/_auth/chat/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/choose-wallet': {
      id: '/_layout/choose-wallet'
      path: '/choose-wallet'
      fullPath: '/choose-wallet'
      preLoaderRoute: typeof LayoutChooseWalletRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_auth': {
      id: '/_layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_auth/setting/': {
      id: '/_layout/_auth/setting/'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof LayoutAuthSettingIndexRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/profile/': {
      id: '/_layout/_auth/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutAuthProfileIndexRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/chat/': {
      id: '/_layout/_auth/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutAuthChatIndexRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/chat/chat/$id': {
      id: '/_layout/_auth/chat/chat/$id'
      path: '/chat/chat/$id'
      fullPath: '/chat/chat/$id'
      preLoaderRoute: typeof LayoutAuthChatChatIdRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
  }
}

interface LayoutAuthRouteChildren {
  LayoutAuthChatIndexRoute: typeof LayoutAuthChatIndexRoute
  LayoutAuthProfileIndexRoute: typeof LayoutAuthProfileIndexRoute
  LayoutAuthSettingIndexRoute: typeof LayoutAuthSettingIndexRoute
  LayoutAuthChatChatIdRoute: typeof LayoutAuthChatChatIdRoute
}

const LayoutAuthRouteChildren: LayoutAuthRouteChildren = {
  LayoutAuthChatIndexRoute: LayoutAuthChatIndexRoute,
  LayoutAuthProfileIndexRoute: LayoutAuthProfileIndexRoute,
  LayoutAuthSettingIndexRoute: LayoutAuthSettingIndexRoute,
  LayoutAuthChatChatIdRoute: LayoutAuthChatChatIdRoute,
}

const LayoutAuthRouteWithChildren = LayoutAuthRoute._addFileChildren(
  LayoutAuthRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthRoute: typeof LayoutAuthRouteWithChildren
  LayoutChooseWalletRoute: typeof LayoutChooseWalletRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthRoute: LayoutAuthRouteWithChildren,
  LayoutChooseWalletRoute: LayoutChooseWalletRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
